## Machine Learning Model on Refugee Population Forecasting and Humanitarian Resource Planning System for Kenya

### 1. Introduction

Kenya accommodates populations displaced by conflict, persecution, climate shocks, and political instability originating from across the region including Somalia, South Sudan, the Democratic Republic of Congo, Ethiopia, Burundi, and Rwanda, among 39 origin countries identified in this dataset.

Several organizations work together to support refugees in Kenya:
1. Department of Refugee Services (DRS): The Kenyan government agency responsible for refugee registration, camp management, policy implementation, and ensuring compliance with the Refugee Act of 2021.
2. United Nations High Commissioner for Refugees (UNHCR): Coordinates the overall refugee response, manages refugee registration and data, mobilizes international funding, and promotes refugee protection.
3. World Food Programme (WFP): Provides food assistance through food distribution and Cash and Voucher Assistance (CVA) programmes to improve food security.
4. Kenya Red Cross Society (KRCS): Delivers frontline humanitarian services, including emergency medical care, disaster response, water supply, family tracing, and support for new refugee arrivals at border entry points.

Together, these organizations form an integrated humanitarian system that provides protection, food, healthcare, and essential services to refugees across Kenya.

### 2. Problem Statement

Kenya hosts one of the largest refugee populations in sub-Saharan Africa, making effective humanitarian planning essential. However, resource planning is often based on current or historical population data rather than future forecasts, limiting preparedness for sudden increases in refugee arrivals.

Key challenges identified from the HDX HAPI dataset include:

1. Rapid population changes that increase demand for food, healthcare, shelter, and other essential services.
2. Diverse demographic groups with different ages, genders, and vulnerabilities that require tailored support.
3. Different population categories (e.g., refugees and asylum seekers) with distinct humanitarian needs.
4. Delays in resource deployment, making it difficult to respond quickly to population surges.
5. Limited use of historical data for forecasting despite decades of available records.

These challenges highlight the need for a machine learning-based forecasting approach to support better resource planning and decision-making for refugee assistance in Kenya.

### 3. Project Objectives

#### 3.1 Primary Objective

To design, develop, and validate a machine learning forecasting system that predicts Kenya's refugee and asylum-seeker population levels disaggregated by origin country, population group, gender, and age cohort with a forecasting horizon of 6 to 24 months, and to translate these forecasts into quantified humanitarian resource planning recommendations.

#### 3.2 Specific Objectives

1. Explore the HDX HAPI Kenya dataset to identify population trends, demographic patterns, and changes over time.
2. Create relevant features to improve forecasting performance.
3. Develop and compare forecasting models to predict refugee population trends.
4. Generate population forecasts by refugee category, age, gender, and country of origin.
5. Estimate humanitarian resource needs based on the forecasted population.
6. Evaluate model performance using standard forecasting metrics (RMSE, MAE, and MAPE).
7. Provide recommendations to support data-driven humanitarian planning and decision-making in Kenya.

### 4) Data Understanding

The HDX HAPI dataset covers 25 years (2001–2025) with 27,664 records across four population groups: Refugees (REF), Asylum Seekers (ASY), Host Community (HST), and Others of Concern (OOC) disaggregated by gender and five age cohorts.

In [4]:
%pip install pandas matplotlib seaborn

Requirement already satisfied: pandas in c:\users\pc\miniconda3\lib\site-packages (3.0.3)
Requirement already satisfied: matplotlib in c:\users\pc\miniconda3\lib\site-packages (3.11.0)
Requirement already satisfied: seaborn in c:\users\pc\miniconda3\lib\site-packages (0.13.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pc\miniconda3\lib\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pc\miniconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\pc\miniconda3\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\pc\miniconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\pc\miniconda3\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\pc\miniconda3\lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\pc\miniconda3\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\pc\miniconda3\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=9 in c:\users\pc\miniconda3\lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\pc\miniconda3\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in c:\users\pc\miniconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:

#import libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

Matplotlib is building the font cache; this may take a moment.

In [6]:
#load data
df = pd.read_csv("Kenya_Refugee.csv")

Descriptive analysis/ Data overview

In [7]:
#view the first 5 rows of the dataset
df.head()

,origin_location_code,origin_has_hrp,origin_in_gho,asylum_location_code,asylum_has_hrp,asylum_in_gho,population_group,gender,age_range,min_age,max_age,population,reference_period_start,reference_period_end
0,AFG,True,True,KEN,False,True,ASY,f,0-4,0.0,4.0,0,2020-01-01,2020-12-31
1,AFG,True,True,KEN,False,True,ASY,f,5-11,5.0,11.0,0,2020-01-01,2020-12-31
2,AFG,True,True,KEN,False,True,ASY,f,12-17,12.0,17.0,0,2020-01-01,2020-12-31
3,AFG,True,True,KEN,False,True,ASY,f,18-59,18.0,59.0,0,2020-01-01,2020-12-31
4,AFG,True,True,KEN,False,True,ASY,f,60+,60.0,NaN,0,2020-01-01,2020-12-31

In [8]:
#total rows and columns
df.shape
#dataset has 27,664 rows and 15 columns

(27664, 14)

In [9]:
df.info()
#dataset has a mix of categorical and numerical data
#no missing values

<class 'pandas.DataFrame'>
RangeIndex: 27664 entries, 0 to 27663
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   origin_location_code    27664 non-null  str
 1   origin_has_hrp          27664 non-null  bool
 2   origin_in_gho           27664 non-null  bool
 3   asylum_location_code    27664 non-null  str
 4   asylum_has_hrp          27664 non-null  bool
 5   asylum_in_gho           27664 non-null  bool
 6   population_group        27664 non-null  str
 7   gender                  27664 non-null  str
 8   age_range               27664 non-null  str
 9   min_age                 21280 non-null  float64
 10  max_age                 17024 non-null  float64
 11  population              27664 non-null  int64
 12  reference_period_start  27664 non-null  str
 13  reference_period_end    27664 non-null  str
dtypes: bool(4), float64(2), int64(1), str(7)
memory usage: 2.2 MB

In [10]:
#statistical data (descriptive statistics)
df.describe()

           min_age      max_age     population
count  21280.00000  17024.00000   27664.000000
mean      19.00000     22.75000    1409.757591
std       21.39209     21.42929   13881.284560
min        0.00000      4.00000       0.000000
25%        5.00000      9.25000       0.000000
50%       12.00000     14.00000       0.000000
75%       18.00000     27.50000      17.000000
max       60.00000     59.00000  517666.000000

In [11]:
df['min_age'].value_counts()

min_age
0.0     4256
5.0     4256
12.0    4256
18.0    4256
60.0    4256
Name: count, dtype: int64

In [12]:
df['max_age'].value_counts()

max_age
4.0     4256
11.0    4256
17.0    4256
59.0    4256
Name: count, dtype: int64

In [13]:
print(df.value_counts())

origin_location_code  origin_has_hrp  origin_in_gho  asylum_location_code  asylum_has_hrp  asylum_in_gho  population_group  gender  age_range  min_age  max_age  population  reference_period_start  reference_period_end
AFG                   True            True           KEN                   False           True           ASY               f       0-4        0.0      4.0      0           2020-01-01              2020-12-31              1
                                                                                                                                    5-11       5.0      11.0     0           2020-01-01              2020-12-31              1
                                                                                                                                    12-17      12.0     17.0     0           2020-01-01              2020-12-31              1
                                                                                                                                    18-59      18.0     59.0     0           2020-01-01              2020-12-31              1
                                                                                                                            m       0-4        0.0      4.0      0           2020-01-01              2020-12-31              1
                                                                                                                                                                                                                            ..
ZWE                   False           False          KEN                   False           True           REF               f       18-59      18.0     59.0     0           2025-01-01              2025-12-31              1
                                                                                                                            m       0-4        0.0      4.0      0           2025-01-01              2025-12-31              1
                                                                                                                                    5-11       5.0      11.0     8           2025-01-01              2025-12-31              1
                                                                                                                                    12-17      12.0     17.0     0           2025-01-01              2025-12-31              1
                                                                                                                                    18-59      18.0     59.0     0           2025-01-01              2025-12-31              1
Name: count, Length: 17024, dtype: int64

In [14]:
#list columns
df.columns.tolist()

['origin_location_code',
 'origin_has_hrp',
 'origin_in_gho',
 'asylum_location_code',
 'asylum_has_hrp',
 'asylum_in_gho',
 'population_group',
 'gender',
 'age_range',
 'min_age',
 'max_age',
 'population',
 'reference_period_start',
 'reference_period_end']

2. DATA CLEANING

In [15]:
#filter for assylum in kenya
df = df[df['asylum_location_code']=='KEN']
df

,origin_location_code,origin_has_hrp,origin_in_gho,asylum_location_code,asylum_has_hrp,asylum_in_gho,population_group,gender,age_range,min_age,max_age,population,reference_period_start,reference_period_end
0,AFG,True,True,KEN,False,True,ASY,f,0-4,0.0,4.0,0,2020-01-01,2020-12-31
1,AFG,True,True,KEN,False,True,ASY,f,5-11,5.0,11.0,0,2020-01-01,2020-12-31
2,AFG,True,True,KEN,False,True,ASY,f,12-17,12.0,17.0,0,2020-01-01,2020-12-31
3,AFG,True,True,KEN,False,True,ASY,f,18-59,18.0,59.0,0,2020-01-01,2020-12-31
4,AFG,True,True,KEN,False,True,ASY,f,60+,60.0,NaN,0,2020-01-01,2020-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27659,ZWE,False,False,KEN,False,True,REF,m,12-17,12.0,17.0,0,2025-01-01,2025-12-31
27660,ZWE,False,False,KEN,False,True,REF,m,18-59,18.0,59.0,0,2025-01-01,2025-12-31
27661,ZWE,False,False,KEN,False,True,REF,m,60+,60.0,NaN,0,2025-01-01,2025-12-31
27662,ZWE,False,False,KEN,False,True,REF,m,all,NaN,NaN,8,2025-01-01,2025-12-31
27663,ZWE,False,False,KEN,False,True,REF,all,all,NaN,NaN,8,2025-01-01,2025-12-31

In [16]:
df.head(10)

,origin_location_code,origin_has_hrp,origin_in_gho,asylum_location_code,asylum_has_hrp,asylum_in_gho,population_group,gender,age_range,min_age,max_age,population,reference_period_start,reference_period_end
0,AFG,True,True,KEN,False,True,ASY,f,0-4,0.0,4.0,0,2020-01-01,2020-12-31
1,AFG,True,True,KEN,False,True,ASY,f,5-11,5.0,11.0,0,2020-01-01,2020-12-31
2,AFG,True,True,KEN,False,True,ASY,f,12-17,12.0,17.0,0,2020-01-01,2020-12-31
3,AFG,True,True,KEN,False,True,ASY,f,18-59,18.0,59.0,0,2020-01-01,2020-12-31
4,AFG,True,True,KEN,False,True,ASY,f,60+,60.0,NaN,0,2020-01-01,2020-12-31
5,AFG,True,True,KEN,False,True,ASY,f,all,NaN,NaN,0,2020-01-01,2020-12-31
6,AFG,True,True,KEN,False,True,ASY,m,0-4,0.0,4.0,0,2020-01-01,2020-12-31
7,AFG,True,True,KEN,False,True,ASY,m,5-11,5.0,11.0,0,2020-01-01,2020-12-31
8,AFG,True,True,KEN,False,True,ASY,m,12-17,12.0,17.0,0,2020-01-01,2020-12-31
9,AFG,True,True,KEN,False,True,ASY,m,18-59,18.0,59.0,8,2020-01-01,2020-12-31

In [17]:
df.tail(10)

,origin_location_code,origin_has_hrp,origin_in_gho,asylum_location_code,asylum_has_hrp,asylum_in_gho,population_group,gender,age_range,min_age,max_age,population,reference_period_start,reference_period_end
27654,ZWE,False,False,KEN,False,True,REF,f,18-59,18.0,59.0,0,2025-01-01,2025-12-31
27655,ZWE,False,False,KEN,False,True,REF,f,60+,60.0,NaN,0,2025-01-01,2025-12-31
27656,ZWE,False,False,KEN,False,True,REF,f,all,NaN,NaN,0,2025-01-01,2025-12-31
27657,ZWE,False,False,KEN,False,True,REF,m,0-4,0.0,4.0,0,2025-01-01,2025-12-31
27658,ZWE,False,False,KEN,False,True,REF,m,5-11,5.0,11.0,8,2025-01-01,2025-12-31
27659,ZWE,False,False,KEN,False,True,REF,m,12-17,12.0,17.0,0,2025-01-01,2025-12-31
27660,ZWE,False,False,KEN,False,True,REF,m,18-59,18.0,59.0,0,2025-01-01,2025-12-31
27661,ZWE,False,False,KEN,False,True,REF,m,60+,60.0,NaN,0,2025-01-01,2025-12-31
27662,ZWE,False,False,KEN,False,True,REF,m,all,NaN,NaN,8,2025-01-01,2025-12-31
27663,ZWE,False,False,KEN,False,True,REF,all,all,NaN,NaN,8,2025-01-01,2025-12-31

In [18]:
#drop 'all' on gender
df = df[df['gender'] != 'all']
print(df['gender'].unique())

<StringArray>
['f', 'm']
Length: 2, dtype: str

In [19]:
#remove missing values from min_age & max_age column
df=df.dropna(subset=['min_age','max_age'])
df.head(20)

,origin_location_code,origin_has_hrp,origin_in_gho,asylum_location_code,asylum_has_hrp,asylum_in_gho,population_group,gender,age_range,min_age,max_age,population,reference_period_start,reference_period_end
0,AFG,True,True,KEN,False,True,ASY,f,0-4,0.0,4.0,0,2020-01-01,2020-12-31
1,AFG,True,True,KEN,False,True,ASY,f,5-11,5.0,11.0,0,2020-01-01,2020-12-31
2,AFG,True,True,KEN,False,True,ASY,f,12-17,12.0,17.0,0,2020-01-01,2020-12-31
3,AFG,True,True,KEN,False,True,ASY,f,18-59,18.0,59.0,0,2020-01-01,2020-12-31
6,AFG,True,True,KEN,False,True,ASY,m,0-4,0.0,4.0,0,2020-01-01,2020-12-31
7,AFG,True,True,KEN,False,True,ASY,m,5-11,5.0,11.0,0,2020-01-01,2020-12-31
8,AFG,True,True,KEN,False,True,ASY,m,12-17,12.0,17.0,0,2020-01-01,2020-12-31
9,AFG,True,True,KEN,False,True,ASY,m,18-59,18.0,59.0,8,2020-01-01,2020-12-31
13,AFG,True,True,KEN,False,True,REF,f,0-4,0.0,4.0,0,2020-01-01,2020-12-31
14,AFG,True,True,KEN,False,True,REF,f,5-11,5.0,11.0,0,2020-01-01,2020-12-31
15,AFG,True,True,KEN,False,True,REF,f,12-17,12.0,17.0,5,2020-01-01,2020-12-31
16,AFG,True,True,KEN,False,True,REF,f,18-59,18.0,59.0,0,2020-01-01,2020-12-31
19,AFG,True,True,KEN,False,True,REF,m,0-4,0.0,4.0,0,2020-01-01,2020-12-31
20,AFG,True,True,KEN,False,True,REF,m,5-11,5.0,11.0,0,2020-01-01,2020-12-31
21,AFG,True,True,KEN,False,True,REF,m,12-17,12.0,17.0,6,2020-01-01,2020-12-31
22,AFG,True,True,KEN,False,True,REF,m,18-59,18.0,59.0,0,2020-01-01,2020-12-31
26,BDI,False,False,KEN,False,True,ASY,f,0-4,0.0,4.0,796,2020-01-01,2020-12-31
27,BDI,False,False,KEN,False,True,ASY,f,5-11,5.0,11.0,754,2020-01-01,2020-12-31
28,BDI,False,False,KEN,False,True,ASY,f,12-17,12.0,17.0,455,2020-01-01,2020-12-31
29,BDI,False,False,KEN,False,True,ASY,f,18-59,18.0,59.0,1744,2020-01-01,2020-12-31

In [20]:
df.shape

(6832, 14)

In [21]:
#remove 'all' in age range
df = df[df['age_range'] != 'all']
print(df['age_range'].unique())

<StringArray>
['0-4', '5-11', '12-17', '18-59']
Length: 4, dtype: str

In [22]:
df['age_range'].unique()

<StringArray>
['0-4', '5-11', '12-17', '18-59']
Length: 4, dtype: str

In [23]:
#check for duplicates
df.duplicated().sum()

np.int64(0)